version: 1.0.0.{build}

os: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

build_script:
- ps: .\release.ps1

artifacts:
- path: .\build\Packages\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: jSR2vFuKiW2kycU/tdAsaT6lPf1uk8Bn2D/K3pWY5ZIHn/JNXvNOHwRp00Yfb7zB
  on:
    branch: master
    appveyor_repo_tag: true

- provider: NuGet
  name: PreRelease
  server: https://ci.appveyor.com/nuget/eknowledger
  api_key:
    secure: CNHgfJDRHjWAeAcL3WWpY9DpgEQLfYi9w1w0FoT7+Qc=
  skip_symbols: false
  on:
     branch: master

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f ".\build\Eknowledger.Language.Xpress.Test.coverage.xml"

# use codecov python package. Requires python to be available, which it is on AppVeyor machine image, and then we have to install the codecov package
#after_test:
#- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
#- pip install codecov
#- codecov -f "XPress_coverage.xml"

