version: 1.0.{build}

image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: Eknowledger.Language.Xpress.sln
  verbosity: minimal

test:
  assemblies:
    only:
      - Eknowledger.Language.Xpress.Test.dll

test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:".\src\Eknowledger.Language.Xpress.Test\bin\Debug\Eknowledger.Language.Xpress.Test.dll" -filter:"+[Eknowledger.Language.Xpress*]* -[Eknowledger.Language.Xpress.Test*]*" -output:".\XPress_coverage.xml"
- codecov -f "XPress_coverage.xml"
